version: '3.8'

services:
  node_test:
    build:
      context: ./
    container_name: node_test_container
    ports:
      - "3000:3000"
    volumes:
      - ./node_test:/app
      - /app/node_modules
    networks:
      - my_network


networks:
  my_network:
    driver: bridge
